name: FakeStackOverflow CI
on: # Controls when the action will run.
  # Triggers the workflow on push or pull request events but only for the master branch. If you want to trigger the action on other branches, add here
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-test: #
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Launch MongoDB Server
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: "8.0"

      - name: Install all dependencies from root
        if: ${{ always() }}
        run: npm i

      - name: Lint all folders
        if: ${{ always() }}
        run: npm run lint --workspaces=true

      - name: Build frontend
        if: ${{ always() }}
        env:
          REACT_APP_SERVER_URL: http://localhost:8000
        run: cd client; npm run build

      - name: Build backend server
        if: ${{ always() }}
        env:
          # Pass the environmental variables for the backend tests to use
          MONGODB_URI: mongodb://localhost:27017
          CLIENT_URL: http://localhost:3000
          PORT: 8000
          AWS_ACCESS_KEY_ID: AKIA2OP6WA2KPVPRV3FZ
          AWS_SECRET_ACCESS_KEY: LWFrJ/gJE1Np/zbfqhcZRzwJqQjNcN/YQ4bzYPQc
          AWS_REGION: us-east-1
          AWS_S3_BUCKET_NAME: fakesoimgs
          JDOODLE_API_URL: https://api.jdoodle.com/v1/execute
          JDOODLE_CLIENT_ID: e399c7b149f48f5545400db501d4266c
          JDOODLE_CLIENT_SECRET: 6b114d6c8810d0eb1580b2ee1b0e43a5c4ef712be99287ec803f3e5d30a317a4
        run: |
          cd server

          npm run start & sleep 10

          echo "Checking if the server is running..."
          curl --fail 'http://localhost:8000/question/getQuestion?order=newest&search=' || (echo "Server failed to start" && killall node && exit 1)

          echo "Server started successfully. Now stopping..."
          killall node

      - name: Test backend server
        if: ${{ always() }}
        env:
          REACT_APP_SERVER_URL: http://localhost:8000
        run: cd server; npm test
